name: GitHub Actions Demo -  JIRA integration
run-name: ${{ github.actor }} is testing out jira integration
on: [push]
jobs:
  jira:
    runs-on: ubuntu-latest
    steps:
      - name: Jira Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Comment on issue
        uses: atlassian/gajira-comment@v3
        with:
          issue: DATA-367
          comment: "${{ github.event.pusher.name }} pushed to repository: ${{ github.event.repository.full_name }}"


        